# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rpostf}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Phil Hofmann"]
  s.date = %q{2010-09-01}
  s.description = %q{generate PostFinance (Swiss Post) URLs and vaildate responses}
  s.email = %q{phil@branch14.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/hash.rb",
     "lib/rpostf.rb",
     "lib/string.rb",
     "rpostf.gemspec",
     "test/helper.rb",
     "test/test_rpostf.rb"
  ]
  s.homepage = %q{http://github.com/branch14/rpostf}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{PostFinance (Swiss Post) Payment Gateway API}
  s.test_files = [
    "test/helper.rb",
     "test/rpostf/params.rb",
     "test/test_rpostf.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

